apiVersion : apps/v1
kind: Deployment
metadata:
  name: "menukubernetes-313d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "menukubernetes-313d"
  template:
    metadata:
      labels:
        app: "menukubernetes-313d"
    spec:
      containers:
        - name: "menukubernetes-313d"
          image: "finalcontainer15.azurecr.io/menukubernetes"
          ports:
          - containerPort: 80