on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: finalcontainer15.azurecr.io
        username: ${{ secrets.acr_finalcontainer15_username }}
        password: ${{ secrets.acr_finalcontainer15_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/OrderItemWebAPI" -f  "OrderItemWebAPI/Dockerfile" -t finalcontainer15.azurecr.io/menukubernetes:${{ github.sha }} --label dockerfile-path=OrderItemWebAPI/Dockerfile
        docker push finalcontainer15.azurecr.io/menukubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_menukubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep menukubernetesac22 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace menukubernetesac22`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: menukubernetesac22
        container-registry-url: finalcontainer15.azurecr.io
        container-registry-username: ${{ secrets.acr_finalcontainer15_username }}
        container-registry-password: ${{ secrets.acr_finalcontainer15_password }}
        secret-name: menukubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: menukubernetesac22
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          finalcontainer15.azurecr.io/menukubernetes:${{ github.sha }}
        imagepullsecrets: |
          menukubernetdockerauth
